jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: "actions/checkout@v1"
      - name: "Run hlint"
        run: "curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s src test bench"
name: "HLint checks"
on:
  - push
